// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosweightedgovernancesdk/delegation/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af039e53996b72a6, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af039e53996b72a6, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryStakingEligibilityRequest defines the QueryStakingEligibilityRequest message.
type QueryStakingEligibilityRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryStakingEligibilityRequest) Reset()         { *m = QueryStakingEligibilityRequest{} }
func (m *QueryStakingEligibilityRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStakingEligibilityRequest) ProtoMessage()    {}
func (*QueryStakingEligibilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af039e53996b72a6, []int{2}
}
func (m *QueryStakingEligibilityRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakingEligibilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakingEligibilityRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakingEligibilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakingEligibilityRequest.Merge(m, src)
}
func (m *QueryStakingEligibilityRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakingEligibilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakingEligibilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakingEligibilityRequest proto.InternalMessageInfo

func (m *QueryStakingEligibilityRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryStakingEligibilityResponse defines the QueryStakingEligibilityResponse message.
type QueryStakingEligibilityResponse struct {
	IsEligible    bool   `protobuf:"varint,1,opt,name=is_eligible,json=isEligible,proto3" json:"is_eligible,omitempty"`
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	IsVesting     bool   `protobuf:"varint,3,opt,name=is_vesting,json=isVesting,proto3" json:"is_vesting,omitempty"`
	VestedAmount  int64  `protobuf:"varint,4,opt,name=vested_amount,json=vestedAmount,proto3" json:"vested_amount,omitempty"`
	VestingAmount int64  `protobuf:"varint,5,opt,name=vesting_amount,json=vestingAmount,proto3" json:"vesting_amount,omitempty"`
}

func (m *QueryStakingEligibilityResponse) Reset()         { *m = QueryStakingEligibilityResponse{} }
func (m *QueryStakingEligibilityResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStakingEligibilityResponse) ProtoMessage()    {}
func (*QueryStakingEligibilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af039e53996b72a6, []int{3}
}
func (m *QueryStakingEligibilityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakingEligibilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakingEligibilityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakingEligibilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakingEligibilityResponse.Merge(m, src)
}
func (m *QueryStakingEligibilityResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakingEligibilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakingEligibilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakingEligibilityResponse proto.InternalMessageInfo

func (m *QueryStakingEligibilityResponse) GetIsEligible() bool {
	if m != nil {
		return m.IsEligible
	}
	return false
}

func (m *QueryStakingEligibilityResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *QueryStakingEligibilityResponse) GetIsVesting() bool {
	if m != nil {
		return m.IsVesting
	}
	return false
}

func (m *QueryStakingEligibilityResponse) GetVestedAmount() int64 {
	if m != nil {
		return m.VestedAmount
	}
	return 0
}

func (m *QueryStakingEligibilityResponse) GetVestingAmount() int64 {
	if m != nil {
		return m.VestingAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmosweightedgovernancesdk.delegation.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmosweightedgovernancesdk.delegation.v1.QueryParamsResponse")
	proto.RegisterType((*QueryStakingEligibilityRequest)(nil), "cosmosweightedgovernancesdk.delegation.v1.QueryStakingEligibilityRequest")
	proto.RegisterType((*QueryStakingEligibilityResponse)(nil), "cosmosweightedgovernancesdk.delegation.v1.QueryStakingEligibilityResponse")
}

func init() {
	proto.RegisterFile("cosmosweightedgovernancesdk/delegation/v1/query.proto", fileDescriptor_af039e53996b72a6)
}

var fileDescriptor_af039e53996b72a6 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0xce, 0x34, 0xbf, 0xe6, 0x67, 0xa6, 0x56, 0x70, 0x2c, 0x12, 0x82, 0x6e, 0xca, 0x8a, 0x50,
	0x0b, 0xd9, 0x61, 0x5b, 0x14, 0x14, 0x14, 0x2c, 0x14, 0xb4, 0x5e, 0xea, 0x2a, 0x1e, 0xbc, 0x84,
	0x49, 0xf7, 0x65, 0x3a, 0x64, 0x33, 0xb3, 0xdd, 0x99, 0xac, 0x06, 0xf1, 0xe2, 0x27, 0x10, 0xfc,
	0x12, 0x1e, 0xfd, 0x0c, 0x82, 0xd0, 0x83, 0x87, 0x82, 0x17, 0x4f, 0x22, 0x89, 0xe0, 0xa7, 0x10,
	0x24, 0x33, 0x13, 0x6a, 0xa9, 0x95, 0x46, 0xbc, 0x2c, 0x33, 0xcf, 0xbc, 0xcf, 0xf3, 0x3e, 0xef,
	0x9f, 0xc5, 0xd7, 0x77, 0x94, 0xee, 0x2b, 0xfd, 0x0c, 0x04, 0xdf, 0x35, 0x90, 0x72, 0x55, 0x42,
	0x21, 0x99, 0xdc, 0x01, 0x9d, 0xf6, 0x68, 0x0a, 0x19, 0x70, 0x66, 0x84, 0x92, 0xb4, 0x8c, 0xe9,
	0xde, 0x00, 0x8a, 0x61, 0x94, 0x17, 0xca, 0x28, 0x72, 0xed, 0x0f, 0xb4, 0xe8, 0x90, 0x16, 0x95,
	0x71, 0xf3, 0x3c, 0xeb, 0x0b, 0xa9, 0xa8, 0xfd, 0x3a, 0x76, 0x73, 0xd5, 0xb1, 0x69, 0x97, 0x69,
	0x70, 0xb2, 0xb4, 0x8c, 0xbb, 0x60, 0x58, 0x4c, 0x73, 0xc6, 0x85, 0x74, 0x5c, 0x17, 0x7b, 0xe3,
	0xf4, 0x06, 0x73, 0x56, 0xb0, 0xbe, 0xf6, 0xbc, 0x25, 0xae, 0xb8, 0xb2, 0x47, 0x3a, 0x39, 0x79,
	0xf4, 0x12, 0x57, 0x8a, 0x67, 0x40, 0x59, 0x2e, 0x28, 0x93, 0x52, 0x19, 0x4b, 0xf6, 0x9c, 0x70,
	0x09, 0x93, 0x87, 0x13, 0x37, 0xdb, 0x56, 0x28, 0x81, 0xbd, 0x01, 0x68, 0x13, 0xf6, 0xf0, 0x85,
	0x23, 0xa8, 0xce, 0x95, 0xd4, 0x40, 0x1e, 0xe3, 0x9a, 0x4b, 0xd8, 0x40, 0xcb, 0x68, 0x65, 0x61,
	0x2d, 0x8e, 0x4e, 0xdd, 0x93, 0xc8, 0x49, 0x6d, 0xd4, 0xf7, 0xbf, 0xb4, 0x2a, 0x6f, 0xbf, 0xbf,
	0x5b, 0x45, 0x89, 0xd7, 0x0a, 0x6f, 0xe1, 0xc0, 0x26, 0x7b, 0x64, 0x58, 0x4f, 0x48, 0xbe, 0x99,
	0x09, 0x2e, 0xba, 0x22, 0x13, 0x66, 0xe8, 0xed, 0x90, 0x06, 0xfe, 0x9f, 0xa5, 0x69, 0x01, 0xda,
	0x25, 0xae, 0x27, 0xd3, 0x6b, 0xf8, 0x01, 0xe1, 0xd6, 0x89, 0x64, 0xef, 0xba, 0x85, 0x17, 0x84,
	0xee, 0x80, 0x7d, 0xc9, 0xc0, 0x2a, 0x9c, 0x49, 0xb0, 0xd0, 0x9b, 0x1e, 0x21, 0x17, 0x71, 0xad,
	0x00, 0xa6, 0x95, 0x6c, 0xcc, 0x59, 0x75, 0x7f, 0x23, 0x97, 0x31, 0x16, 0xba, 0x53, 0x82, 0x36,
	0x42, 0xf2, 0x46, 0xd5, 0xf2, 0xea, 0x42, 0x3f, 0x71, 0x00, 0xb9, 0x82, 0x17, 0x27, 0x6f, 0x90,
	0x76, 0x58, 0x5f, 0x0d, 0xa4, 0x69, 0xfc, 0xb7, 0x8c, 0x56, 0xaa, 0xc9, 0x59, 0x07, 0xde, 0xb5,
	0x18, 0xb9, 0x8a, 0xcf, 0x79, 0x81, 0x69, 0xd4, 0xbc, 0x8d, 0x5a, 0xf4, 0xa8, 0x0b, 0x5b, 0xfb,
	0x58, 0xc5, 0xf3, 0xb6, 0x0e, 0xf2, 0x1e, 0xe1, 0x9a, 0xeb, 0x15, 0xb9, 0x3d, 0x43, 0x7b, 0x8f,
	0x0f, 0xb1, 0x79, 0xe7, 0x6f, 0xe9, 0xae, 0x6f, 0xe1, 0xcd, 0x57, 0x9f, 0xbe, 0xbd, 0x99, 0x5b,
	0x27, 0x31, 0x05, 0xb9, 0x3b, 0xa1, 0xa5, 0xed, 0x43, 0x89, 0xb6, 0x76, 0x0d, 0xff, 0xed, 0x3e,
	0x92, 0x1f, 0x08, 0x93, 0xe3, 0x13, 0x21, 0xf7, 0x67, 0x75, 0x74, 0xe2, 0x4a, 0x34, 0xb7, 0xfe,
	0x85, 0x94, 0x2f, 0x74, 0xdb, 0x16, 0xba, 0x45, 0xee, 0xcd, 0x50, 0xa8, 0x47, 0xfd, 0x5a, 0x59,
	0x3d, 0xfa, 0xc2, 0x6f, 0xe5, 0xcb, 0x8d, 0x07, 0xfb, 0xa3, 0x00, 0x1d, 0x8c, 0x02, 0xf4, 0x75,
	0x14, 0xa0, 0xd7, 0xe3, 0xa0, 0x72, 0x30, 0x0e, 0x2a, 0x9f, 0xc7, 0x41, 0xe5, 0x69, 0xec, 0x6c,
	0xb7, 0xa7, 0xbe, 0x8f, 0x64, 0x4a, 0x7b, 0xf4, 0xf9, 0xaf, 0x79, 0xcc, 0x30, 0x07, 0xdd, 0xad,
	0xd9, 0x3f, 0x75, 0xfd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x5d, 0x55, 0xc1, 0xb8, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// StakingEligibility Queries a list of StakingEligibility items.
	StakingEligibility(ctx context.Context, in *QueryStakingEligibilityRequest, opts ...grpc.CallOption) (*QueryStakingEligibilityResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmosweightedgovernancesdk.delegation.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StakingEligibility(ctx context.Context, in *QueryStakingEligibilityRequest, opts ...grpc.CallOption) (*QueryStakingEligibilityResponse, error) {
	out := new(QueryStakingEligibilityResponse)
	err := c.cc.Invoke(ctx, "/cosmosweightedgovernancesdk.delegation.v1.Query/StakingEligibility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// StakingEligibility Queries a list of StakingEligibility items.
	StakingEligibility(context.Context, *QueryStakingEligibilityRequest) (*QueryStakingEligibilityResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) StakingEligibility(ctx context.Context, req *QueryStakingEligibilityRequest) (*QueryStakingEligibilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StakingEligibility not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosweightedgovernancesdk.delegation.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StakingEligibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStakingEligibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StakingEligibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmosweightedgovernancesdk.delegation.v1.Query/StakingEligibility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StakingEligibility(ctx, req.(*QueryStakingEligibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmosweightedgovernancesdk.delegation.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "StakingEligibility",
			Handler:    _Query_StakingEligibility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmosweightedgovernancesdk/delegation/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryStakingEligibilityRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakingEligibilityRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakingEligibilityRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryStakingEligibilityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakingEligibilityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakingEligibilityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VestingAmount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.VestingAmount))
		i--
		dAtA[i] = 0x28
	}
	if m.VestedAmount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.VestedAmount))
		i--
		dAtA[i] = 0x20
	}
	if m.IsVesting {
		i--
		if m.IsVesting {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x12
	}
	if m.IsEligible {
		i--
		if m.IsEligible {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryStakingEligibilityRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryStakingEligibilityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsEligible {
		n += 2
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.IsVesting {
		n += 2
	}
	if m.VestedAmount != 0 {
		n += 1 + sovQuery(uint64(m.VestedAmount))
	}
	if m.VestingAmount != 0 {
		n += 1 + sovQuery(uint64(m.VestingAmount))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStakingEligibilityRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakingEligibilityRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakingEligibilityRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStakingEligibilityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakingEligibilityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakingEligibilityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsEligible", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsEligible = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsVesting", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsVesting = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestedAmount", wireType)
			}
			m.VestedAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestedAmount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingAmount", wireType)
			}
			m.VestingAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingAmount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
